<?php
	//Constants used in the site
	define("DB_SERVER", "localhost");
	define("DB_USER", "root");
	define("DB_PASS", "root");
	define("DB_NAME", "gaunkhanekatha");
	define("ADMINEMAIL", 'admin@admin.com');
	//current password is "password", but change it by putting your own passwords sha1 hash below
	define("ADMINPASSWORD", '5baa61e4c9b93f3f0682250b6cf8331b7ee68fd8');

	//Other constats/language keywords
	define("SITENAME", "गाउँ खाने कथा - प्रस्न र उत्तर");
	define("DESCRIPTION", "Traditional game from Nepal, played with proverbs using question and answers... we call it as, Village Eating Story");
	define("SITEURL", "http://gaunkhanekatha.com");
	define("SOURCECODEURL", "http://github.com/deSushil");
	define("GUSER", "info@gaunkhanekatha.com");
	define("GPWD", "");
	define("TWITTER", "GaunKhaneKatha");
	define("SEEANSWER", "उत्तर हेर्नुहोस");
	define("NEXTQUESTION", "अर्को कथा");
	define("HOME", "गृह");
	define("ADD", "थप्नुहोस");
	define("LISTGKK", "संग्रह");
	define("LOGOUT", "बाहिर जानुहोस");
	define("LOGIN", "भित्र छिर्नुहोस");
	define("ABOUT", "हाम्रो बारेमा");
	define("HOMEPAGEHEADER", "गृह पृष्ठ");
	define("GKKPAGEHEADER", "गाउँ खाने कथा");
	define("ABOUTPAGEHEADER", "हाम्रो बारेमा");
	define("LOGINPAGEHEADER", "आफ्नो खाता भित्र छिर्नु होस्");
	define("LISTPAGEHEADER", "गाउँ खाने कथाहरुको संग्रह");
	define("ADDPAGEHEADER", "तपाइको गाउँ खाने कथाहरु थप्नुहोस");
	define("TOTAL", "जम्मा");
	define("PENDING", "थाती");
	define("ACTIVATED", "स्वीकृत");
	define("NEPALIAND", "र");
	define("GKKS", "गाउँ खाने कथाहरु");
	define("QUESTION", "प्रश्न");
	define("ANSWER", "उत्तर");
	define("QUESTIONDETAIL", "गाउँ खाने प्रश्न");
	define("ANSWERDETAIL", "गाउँ खाने उत्तर");
	define("ADDDETAIL", "थप्नुहोस");
	define("USERNAME", "इमेल");
	define("PASSWORD", "पासवोर्ड");
	define("WAIT", "एकै छिन् सोच्नुहोस ");
	define("SUCCESSFULLSUBMISSION","सफलताका साथ् संग्रहित गरियो, धन्यवाद!");
	define("SHORTDATA","अलि छोटो भयो, अलि लामो लेख्नुहोस!");
	define("FIELDEMPTY","कृपया सबै बाकसहरु भर्नुहोस्!");
	define("DELETESUCCESS","उक्त गाउँ खाने कथा हटाइयो!");
	define("DELETEERROR","गाउँ खाने कथा हटाउने प्रक्रियामा खराबी आयो!");
	define("ERRORMESSAGE","माफ गर्नु होला, प्रक्रियामा केहि खराबी आयो!");
	define("NOTALLOWED","यो कार्य गर्न को लागि अनुमति छैन!");
	define("SUCCESSMESSAGE","कार्य सफलताको साथ सम्पन्न गरियो!");
	define("LOGINSUCCESS","तपाई सफलताका साथ् भित्र छिर्नु भयो!");
	define("LOGINERROR","तपाईको इमेल अथवा पस्स्वोर्ड मिलेन!");
	define("LOGOUTSUCCESS","तपाई सफलता का साथ् बाहिर निस्कनु भयो!");
	define("APPROVESUCCESS","गाउँ खाने कथा स्वीकृत गरियो!");
	define("APPROVEERROR","स्वीकृत गर्दा प्रक्रिया मा केहि खराबी आयो!");
	define("EDITSUCCESS","सम्पादन कार्य सफल भयो!");
	define("EDITERROR","सम्पादन प्रक्रियामा खराबी आयो!");
	define("EDITPAGEHEADER", "गाउँ खाने कथा सम्पादन गर्नुहोस!");
	define("EDITBUTTON", "सम्पादन गर्नुहोस!");
	define("FOOTERMESSAGE", "© गाउँ खाने कथा २०१२, केहि अधिकार संरक्षित");
	define("CANCELBUTTON", "रद्द गर्नुहोस");
	define("NAME", "नाम");
	define("NAMEDETAIL", "पुरा नाम लेख्नुहोस");
	define("EMAIL", "इमेल");
	define("EMAILDETAIL", "इमेल ठेगाना लेख्नुहोस");
	define("ADMINNAME", "संचालक");
	define("LOADINGTEXT", "एकै छिन्..");